Controllers/CartController.cs
using eCommerceSitePractice.Data;
using eCommerceSitePractice.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace eCommerceSitePractice.Controllers
{
    public class CartController : Controller
    {
        private readonly ProductContext _context;
        private const string Cart = "ShoppingCart";

        public CartController(ProductContext context)
        {
            _context = context;
        }

        public IActionResult Add(int id)
        {
            Product? productToAdd = _context.Products.Where(p => p.ProductID == id).SingleOrDefault();

            if (productToAdd == null)
            {
                // Product not found
                TempData["Message"] = "That item is no longer in stock";
                return RedirectToAction("Index", "Products");
            }

            CartProductViewModel cartProduct = new()
            {
                ProductID = productToAdd.ProductID,
                Name = productToAdd.Name,
                Price = productToAdd.Price
            };

            List<CartProductViewModel> cartProducts = GetExistingCartData();
            cartProducts.Add(cartProduct);
            WriteShoppingCartCookie(cartProducts);

            TempData["Message"] = "Item added to cart!";
            return RedirectToAction("Index", "Products");
        }

        private void WriteShoppingCartCookie(List<CartProductViewModel> cartProducts)
        {
            string cookieData = JsonConvert.SerializeObject(cartProducts);

            HttpContext.Response.Cookies.Append(Cart, cookieData, new CookieOptions()
            {
                Expires = DateTimeOffset.Now.AddDays(7)
            });
        }

        /// <summary>
        /// Return the current list of video games in the user's shopping cart cookie.
        /// If the cookie does not exist, return an empty list.
        /// </summary>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        private List<CartProductViewModel> GetExistingCartData()
        {
            string? cartCookie = HttpContext.Request.Cookies[Cart];

            if (string.IsNullOrEmpty(cartCookie))
            {
                return new List<CartProductViewModel>();
            }

            return JsonConvert.DeserializeObject<List<CartProductViewModel>>(cartCookie);


        }

        public IActionResult Summary()
        {
            // Read shopping cart cookie and convert to list of CartProductViewModel

            List<CartProductViewModel> cartProducts = GetExistingCartData();
            return View(cartProducts);
        }

        public IActionResult Remove(int id)
        {
            List<CartProductViewModel> cartProducts = GetExistingCartData();
            
            CartProductViewModel? productToRemove = cartProducts.Where(p => p.ProductID == id).FirstOrDefault();
            
            if (productToRemove != null)
            {
                cartProducts.Remove(productToRemove);

                WriteShoppingCartCookie(cartProducts);

                TempData["Message"] = "Item removed from cart!";

                return RedirectToAction("Summary");
            }
            else
            {
                TempData["Message"] = "Item not found in cart";
                return RedirectToAction("Summary");
            }

        }
        
    }
}

Controllers/UsersController.cs
using eCommerceSitePractice.Data;
using eCommerceSitePractice.Models;
using Microsoft.AspNetCore.Mvc;

namespace eCommerceSitePractice.Controllers
{
    public class UsersController : Controller
    {
        private readonly ProductContext _context;
        public UsersController(ProductContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel regModel)
        {
            if (ModelState.IsValid)
            {
                // Map RegisterViewModel data to User object
                User newUser = new()
                {
                    Email = regModel.Email,
                    Password = regModel.Password
                };

                // Add user to database
                _context.Users.Add(newUser);
                await _context.SaveChangesAsync();

                LogUserIn(newUser.Email);

                // Redirect to home page
                return RedirectToAction("Index", "Home");
            }
            return View(regModel);
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel loginModel)
        {
            if (ModelState.IsValid)
            {
                User? u = (from user in _context.Users
                         where user.Email == loginModel.Email &&
                               user.Password == loginModel.Password
                         select user).SingleOrDefault();

                if (u != null)
                {
                    LogUserIn(loginModel.Email);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login credentials.");
                }
            }
            return View(loginModel);
        }

        private void LogUserIn(string email)
        {
            HttpContext.Session.SetString("Email", email);
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor _httpContext
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - The Sweet Shoppe</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/eCommerceSitePractice.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">The Sweet Shoppe</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Product Catalog</a>
                        </li>

                        @{
                            string? userEmail = _httpContext.HttpContext.Session.GetString("Email");    
                        
                            if (userEmail == null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Log In</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Register">User Registration</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Logout">Log Out</a>
                                </li>
                                <li class="nav-item">
                                    Hello @_httpContext.HttpContext.Session.GetString("Email")
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Summary">View Cart
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                                        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l1.313 7h8.17l1.313-7zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2" />
                                    </svg>
                                </a>
                            </li>
                        }


                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - The Sweet Shoppe
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>